<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- windows10.0.19041.0 引入 WinRT 投影，才能调用 NetworkOperatorTetheringManager（移动热点 API） -->
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WinDivertSharp" Version="1.4.3.2" />
  </ItemGroup>

</Project>
